package in.app.onlineassisment.model;
// Generated Jul 3, 2020 3:54:48 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person")
public class Person  {

	private Integer id;
	private PersonType personType;
	private int studentCode;
	private String fname;
	private String lname;
	private int gender;
	private char isUser;
	private int gradeYear;
	private String email;
	private String password;
	private String phoneNum;
	private Date birthDate;
	private Date createdDate;

	public Person() {
	}

	public Person(PersonType personType, int studentCode, String fname, String lname, int gender, char isUser,
			int gradeYear,String email,String password,String phoneNum,Date birthDate, Date createdDate) {
		this.personType = personType;
		this.studentCode = studentCode;
		this.fname = fname;
		this.lname = lname;
		this.gender = gender;
		this.isUser = isUser;
		this.gradeYear = gradeYear;
		this.email = email;
		this.password = password;
		this.phoneNum = phoneNum;
		this.birthDate = birthDate;
		this.createdDate = createdDate;
	}

	

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator = "person_generator")
	@Column(name = "ID", unique = true, nullable = false)
	@GenericGenerator(name="person_generator",	
			  strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator",
		      parameters = {
		    	        @Parameter(name = "person_generator", value = "person_generator"),
		    	        @Parameter(name = "initial_value", value = "1"),
		    	        @Parameter(name = "increment_size", value = "1")
		    	        }	)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSON_TYPE_ID", nullable = false)
	public PersonType getPersonType() {
		return this.personType;
	}

	public void setPersonType(PersonType personType) {
		this.personType = personType;
	}

	@Column(name = "STUDENT_CODE", nullable = false)
	public int getStudentCode() {
		return this.studentCode;
	}

	public void setStudentCode(int studentCode) {
		this.studentCode = studentCode;
	}

	@Column(name = "FNAME", nullable = false, length = 50)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "LNAME", nullable = false, length = 50)
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@Column(name = "GENDER", nullable = false)
	public int getGender() {
		return this.gender;
	}

	public void setGender(int gender) {
		this.gender = gender;
	}

	@Column(name = "IS_USER", nullable = false, length = 1)
	public char getIsUser() {
		return this.isUser;
	}

	public void setIsUser(char isUser) {
		this.isUser = isUser;
	}

	@Column(name = "GRADE_YEAR", nullable = false)
	public int getGradeYear() {
		return this.gradeYear;
	}

	public void setGradeYear(int gradeYear) {
		this.gradeYear = gradeYear;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PASSWORD", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	
	@Column(name = "PHONE_NUM", length = 20)
	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BIRTH_DATE", length = 19)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19 , nullable = false)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	

}
