package in.app.onlineassisment.model;
// Generated Jul 3, 2020 3:54:48 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PersonType generated by hbm2java
 */
@Entity
@Table(name = "person_type")
public class PersonType  {

	private Integer id;
	private String personTypeName;
	private String description;

	public PersonType() {
	}

	public PersonType(String personTypeName) {
		this.personTypeName = personTypeName;
	}
	
	
	@Id
	@Column(name = "ID", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PERSON_TYPE_NAME", nullable = false, length = 50)
	public String getPersonTypeName() {
		return this.personTypeName;
	}

	public void setPersonTypeName(String personTypeName) {
		this.personTypeName = personTypeName;
	}

	@Column(name = "DESCRIPTION", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


}
